# Правило, которое будет срабатывать при недоступности узла (node-exporter)
groups: 
- name: test
  rules:
  - alert: PrometheusTargetMissing
    expr: up == 0
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: "Prometheus target missing (instance {{ $labels.instance }})"
      description: "A Prometheus target has disappeared. An exporter might be crashed. VALUE = {{ $value }}  LABELS: {{ $labels }}"

# Правило, которое будет срабатывать при перезагрузке узла (node-exporter)
  - alert: ServerReboot
    expr: node_boot_time_seconds == 0
    for: 1m
    labels:
      severity: hight
    annotations:
      summary: Prometheus target ServerReboot - server reboot (instance {{ $labels.instance }})
      description: "ServerReboot took more than 1m to complete. VALUE = {{ $value }} LABELS = {{ $labels }}"

# BlackboxSlowProbe — предупреждать, если сайт открывается дольше 5 секунд
  - alert: BlackboxSlowProbe
    expr: avg_over_time(probe_duration_seconds[1m]) > 5
    for: 1m
    labels:
      severity: warning
    annotations:
      summary: Blackbox slow probe (instance {{ $labels.instance }})
      description: "Blackbox probe took more than 1s to complete\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

# BlackboxProbeHttpFailure — реагировать, в случае получения кода ответа с ошибкой работы сайта (более 400).
  - alert: BlackboxProbeHttpFailure
    expr: probe_http_status_code <= 199 OR probe_http_status_code >= 400
    for: 0m
    labels:
      severity: critical
    annotations:
      summary: Blackbox probe HTTP failure (instance {{ $labels.instance }})
      description: "HTTP status code is not 200-399\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"

# Правило, которое будет срабатывать в случае превышения node_load1 значения 0.8 на протяжении 30 секунд.
#  — alert: high_load
#    expr: node_load1 > 0.8
#    for: 30s
#    labels:
#      severity: warning      
#    annotations:
#      summary: "Instance {{ $labels.instance }} under high load"
#      description: "{{ $labels.instance }} of job {{ $labels.job }} is under high load."